apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 2m0s
  url: ssh://git@github.com/SuryanshPratap/infra
  ref:
    branch: master
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 2m0s
  path: ./cluster/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
